---
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  # EnforcedStyle: double_quotes
